### ISSUE TITLE
Fira Code Font Support

### ISSUE THREAD

**Issue by tankerkiller125** [aramk/crayon-syntax-highlighter#416]
It would be awesome if Crayon supported [Fira Code](https://github.com/tonsky/FiraCode) and it's font ligatures.

The following CSS works in other Syntax Highligters but doesn't seem to do anything with Crayon:

```css
@font-face{
    font-family: 'Fira Code';
    src: url('https://cdn.rawgit.com/tonsky/FiraCode/master/distr/eot/FiraCode-Regular.eot?raw=true');
    src: url('https://cdn.rawgit.com/tonsky/FiraCode/master/distr/eot/FiraCode-Regular.eot?raw=true') format('embedded-opentype'),
         url('https://cdn.rawgit.com/tonsky/FiraCode/master/distr/woff2/FiraCode-Regular.woff2?raw=true') format('woff2'),
         url('https://cdn.rawgit.com/tonsky/FiraCode/master/distr/woff/FiraCode-Regular.woff?raw=true') format('woff'),
         url('https://cdn.rawgit.com/tonsky/FiraCode/master/distr/ttf/FiraCode-Regular.ttf?raw=true') format('truetype');
    font-weight: 400;
    font-style: normal;
}
code, pre {
    font-family: 'Fira Code' !important;
    font-size: 1em !important;
    /* Enables font ligatures in browsers */
    font-variant-ligatures: contextual;
    /* Enables font ligatures in IE10+ */
    font-feature-settings: "calt" 1;
}
```

As a note: I do know that Crayon uses a class instead of HTML markup. However even using that does not work. Eg.
```css
.crayon-code, .crayon-pre {
    font-family: 'Fira Code' !important;
    font-size: 1em !important;
    /* Enables font ligatures in browsers */
    font-variant-ligatures: contextual;
    /* Enables font ligatures in IE10+ */
    font-feature-settings: "calt" 1;
}
```
